PortalDoEnsino/src/main/java/br/com/portaldoensino/entity/Curso.java
package br.com.portaldoensino.entity;

import java.io.Serializable;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 *
 * @author jose.bonifacio
 */
@Entity
@Table(name = "curso")
public class Curso implements PersistentEntity<Long>, Serializable {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @NotNull
    private String nome;
    private String descricao;
    @ManyToOne
    private Instituicao instituicao;    
    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "aluno_curso", joinColumns = {
        @JoinColumn(name = "curso_id")}, inverseJoinColumns = {
        @JoinColumn(name = "aluno_id")})
    private List<Usuario> alunos;
    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "professor_curso", joinColumns = {
        @JoinColumn(name = "curso_id")}, inverseJoinColumns = {
        @JoinColumn(name = "professor_id")})
    private List<Usuario> professores;
    private String identificadorCursoAva;
    @Transient
    private boolean modoEdicao;

    public Curso() {
    }

    @Override
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Instituicao getInstituicao() {
        return instituicao;
    }

    public void setInstituicao(Instituicao instituicao) {
        this.instituicao = instituicao;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    
    public List<Usuario> getAlunos() {
        return alunos;
    }

    public void setAlunos(List<Usuario> alunos) {
        this.alunos = alunos;
    }

    public List<Usuario> getProfessores() {
        return professores;
    }

    public void setProfessores(List<Usuario> professores) {
        this.professores = professores;
    }
    
    public void setModoEdicao(boolean modoEdicao) {
        this.modoEdicao = modoEdicao;
    }
    
    public boolean isModoEdicao() {
        return this.modoEdicao;
    }

    public String getIdentificadorCursoAva() {
        return identificadorCursoAva;
    }

    public void setIdentificadorCursoAva(String identificadorCursoAva) {
        this.identificadorCursoAva = identificadorCursoAva;
    }
    
    public boolean ehProfessor(Usuario usuario) {
        if (usuario == null || professores == null) {
            return false;
        }
        for (Usuario professor : professores) {
            if (professor.equals(usuario)) {
                return true;
            }
        }
        return false;
    }
    
    public Set<Usuario> getAlunosSet() {
        Set<Usuario> usuariosList = new HashSet<>(); 
        if (alunos != null && !alunos.isEmpty()) {
            for (Usuario usuario : alunos) {
                usuariosList.add(usuario);
            }
        }
        return usuariosList;
    }
    
    public Set<Usuario> getProfessoresSet() {        
        Set<Usuario> usuariosList = new HashSet<>(); 
        if (professores != null && !professores.isEmpty()) {
            for (Usuario usuario : professores) {
                usuariosList.add(usuario);
            }
        }
        return usuariosList;
    }
 
    public String getUrlCurso() {
        return "<a href=\"http://localhost:8080/PortalDoEnsino/faces/instituicao/curso.xhtml?cursoId=" + id + "\">" + getNome() + "</a>";
    }
    
    @Override
    public boolean isNew() {
        return this.id == null;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 71 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Curso other = (Curso) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return String.valueOf(id);
    }
    
}

PortalDoEnsino/src/main/java/br/com/portaldoensino/entity/Instituicao.java
package br.com.portaldoensino.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 *
 * @author BONIFACIO
 */
@Entity
@Table(name = "instituicao")
public class Instituicao implements PersistentEntity<Long>, Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @NotNull
    private String nome;
    private String descricao;
    @OneToMany(mappedBy = "instituicao",
            fetch = FetchType.EAGER,
            cascade = CascadeType.ALL)
    private List<Curso> cursos;
    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "instituicao_administrador", joinColumns = {
        @JoinColumn(name = "instituicao_id")}, inverseJoinColumns = {
        @JoinColumn(name = "administrador_id")})
    private List<Usuario> administradores;
    private boolean possuiAva;
    @Enumerated
    private InstituicaoTipoAva tipoAva;
    private String tokenAcesso;
    private String enderecoAva;

    public Instituicao() {
    }

    @Override
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public List<Usuario> getAdministradores() {
        return administradores;
    }

    public void setAdministradores(List<Usuario> administradores) {
        this.administradores = administradores;
    }
    
    public Set<Usuario> getAdministradoresSet() {
        Set<Usuario> administradoresList = new HashSet<>();
        if (administradores != null && !administradores.isEmpty()) {
            for (Usuario usuario : administradores) {
                administradoresList.add(usuario);
            }
        }
        return administradoresList;
    }

    public boolean isPossuiAva() {
        return possuiAva;
    }

    public void setPossuiAva(boolean possuiAva) {
        this.possuiAva = possuiAva;
    }

    public List<Curso> getCursos() {
        return cursos;
    }

    public Set<Curso> getCursosSet() {
        Set<Curso> cursosSet = new HashSet<>();
        if (cursos != null && !cursos.isEmpty()) {
            for (Curso curso : this.cursos) {
                cursosSet.add(curso);
            }
        }
        return cursosSet;
    }

    public void setCursos(List<Curso> cursos) {
        this.cursos = cursos;
    }

    public InstituicaoTipoAva getTipoAva() {
        return tipoAva;
    }

    public void setTipoAva(InstituicaoTipoAva tipoAva) {
        this.tipoAva = tipoAva;
    }

    public String getTokenAcesso() {
        return tokenAcesso;
    }

    public void setTokenAcesso(String tokenAcesso) {
        this.tokenAcesso = tokenAcesso;
    }

    public String getEnderecoAva() {
        return enderecoAva;
    }

    public void setEnderecoAva(String enderecoAva) {
        this.enderecoAva = enderecoAva;
    }

    public List<Usuario> getAlunos() {
        List<Usuario> alunos = new ArrayList<>();
        for (Curso curso : cursos) {
            for (Usuario alunoCurso : curso.getAlunos()) {
                if (!alunos.contains(alunoCurso)) {
                    alunos.add(alunoCurso);
                }
            }
        }
        return alunos;
    }

    public List<Usuario> getProfessores() {
        List<Usuario> professores = new ArrayList<>();
        for (Curso curso : cursos) {
            for (Usuario professorCurso : curso.getProfessores()) {
                if (!professores.contains(professorCurso)) {
                    professores.add(professorCurso);
                }
            }
        }
        return professores;
    }

    public Set<Usuario> getAdministradores2() {
        Set<Usuario> administradores2 = new HashSet<>();
        administradores2.addAll(administradores);
        return administradores2;
    }

    public boolean ehAdministrador(Usuario usuario) {
        if (usuario == null || administradores == null) {
            return false;
        }
        return administradores.contains(usuario);
    }

    public String getUrlInstituicao() {
        return "<a href=\"http://localhost:8080/PortalDoEnsino/faces/instituicao/instituicao.xhtml?instituicaoId=" + id + "\">" + getNome() + "</a>";
    }
    
    public String getUrlInstituicao(Instituicao instituicao) {
        return "<a href=\"http://localhost:8080/PortalDoEnsino/faces/instituicao/instituicao.xhtml?instituicaoId=" + instituicao.getId() + "\">" + instituicao.getNome() + "</a>";
    }

    @Override
    public boolean isNew() {
        return this.id == null;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 11 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Instituicao other = (Instituicao) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return String.valueOf(id);
    }

}

PortalDoEnsino/src/main/java/br/com/portaldoensino/entity/Usuario.java
package br.com.portaldoensino.entity;

import br.com.portaldoensino.util.SenhaUtil;
import java.io.Serializable;
import java.util.List;
import java.util.Objects;
import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 *
 * @author jose.bonifacio
 */
@Entity
@Table(name = "usuario")
public class Usuario implements PersistentEntity<Long>, Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @NotNull
    private String email;
    @NotNull
    private String senha;
    @NotNull
    private String nome;
    private String sobrenome;
    private String avatar;
    @NotNull
    private Boolean ativo;
    @OneToMany(mappedBy = "usuario",
            fetch = FetchType.EAGER,
            cascade = CascadeType.ALL)
    private List<UsuarioAmigo> amigos;
    @OneToMany(mappedBy = "usuario",
            fetch = FetchType.EAGER,
            cascade = CascadeType.ALL)
    private List<UsuarioSeguidor> usuariosSeguidos;
    @OneToMany(mappedBy = "tema",
            fetch = FetchType.LAZY,
            cascade = CascadeType.ALL)
    private List<TemaFavorito> temasFavoritos;
    @OneToMany(mappedBy = "usuario",
            fetch = FetchType.EAGER,
            cascade = CascadeType.ALL)
    private List<InstituicaoSeguida> instituicoesSeguidas;

    public Usuario() {
        ativo = true;
    }

    @Override
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = SenhaUtil.getEncryptedPassword(senha);
    }

    public void setSenhaCriptografada(String senhaCriptografada) {
        this.senha = senhaCriptografada;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getSobrenome() {
        return sobrenome;
    }

    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Boolean getAtivo() {
        return ativo;
    }

    public void setAtivo(Boolean ativo) {
        this.ativo = ativo;
    }

    public String getNomeCompleto() {
        return this.nome.concat(" ").concat(this.sobrenome);
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getAvatarUrl() {
        if (avatar == null || avatar.isEmpty()) {
            return "http://localhost:8080/PortalDoEnsino/faces/download?caminhoArquivo="
                    + "C:/PortalDoEnsino/portaldoensino/PortalDoEnsino/src/main/webapp/resources/images/defaultavatar2.png";
        }
        return "http://localhost:8080/PortalDoEnsino/faces/download?caminhoArquivo=" + avatar;
    }

    public List<UsuarioAmigo> getAmigos() {
        return amigos;
    }

    public boolean ehAmigo(Usuario usuario) {
        boolean ehAmigo = false;
        if (usuario == null) {
            return false;
        }
        for (UsuarioAmigo amigo : amigos) {
            if (amigo.getAmigo().getId().equals(usuario.getId())) {
                ehAmigo = true;
            }
        }
        return ehAmigo;
    }

    public boolean ehSeguido(Usuario usuario) {
        boolean ehSeguido = false;
        if (usuario == null) {
            return false;
        }
        for (UsuarioSeguidor usuarioSeguido : usuariosSeguidos) {
            if (usuarioSeguido.getSeguidor().getId().equals(usuario.getId())) {
                ehSeguido = true;
            }
        }
        return ehSeguido;
    }

    public void setAmigos(List<UsuarioAmigo> amigos) {
        this.amigos = amigos;
    }

    public List<UsuarioSeguidor> getUsuariosSeguidos() {
        return usuariosSeguidos;
    }

    public void setUsuariosSeguidos(List<UsuarioSeguidor> usuariosSeguidos) {
        this.usuariosSeguidos = usuariosSeguidos;
    }

    public List<TemaFavorito> getTemasFavoritos() {
        return temasFavoritos;
    }

    public void setTemasFavoritos(List<TemaFavorito> temasFavoritos) {
        this.temasFavoritos = temasFavoritos;
    }

    public List<InstituicaoSeguida> getInstituicoesSeguidas() {
        return instituicoesSeguidas;
    }

    public void setInstituicoesSeguidas(List<InstituicaoSeguida> instituicoesSeguidas) {
        this.instituicoesSeguidas = instituicoesSeguidas;
    }

    public String getUrlPerfil() {
        return "<a href=\"http://localhost:8080/PortalDoEnsino/faces/usuario/visualizar.xhtml?usuarioId=" + id + "\">" + getNomeCompleto() + "</a>";
    }

    public String getUrlPerfil(Usuario usuario) {
        return "<a href=\"http://localhost:8080/PortalDoEnsino/faces/usuario/visualizar.xhtml?usuarioId=" + usuario.getId() + "\">" + usuario.getNomeCompleto() + "</a>";
    }

    @Override
    public boolean isNew() {
        return this.id == null;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Usuario other = (Usuario) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return String.valueOf(id);
    }

}

PortalDoEnsino/src/main/webapp/instituicao/administrarMembrosCurso.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <f:metadata>
        <f:viewParam name="cursoId" value="#{instituicaoView.curso.id}" />
        <f:viewAction action="#{instituicaoView.loadCurso()}" if="#{not empty param['cursoId']}"/>
    </f:metadata>
    <h:body>
        <ui:composition template="/resources/template/layout.xhtml">
            <ui:define name="conteudo">
                <h:form styleClass="tema" rendered="#{sessionController.loggedIn and instituicaoView.curso.instituicao.ehAdministrador(sessionController.usuarioLogado)}"> 
                    <p:fieldset legend="Curso #{instituicaoView.curso.nome}" >                        
                        <p:commandButton value="Voltar para o curso" ajax="false" 
                                         icon="ui-icon-arrowreturn-1-w"
                                         rendered="#{!instituicaoView.curso.new}" action="#{instituicaoView.voltarParaCurso()}"/>
                        <br/>
                        <p:outputLabel value="Convidar aluno: "/>
                        <p:autoComplete id="usuarios" value="#{instituicaoView.usuarioConvidado}" 
                                        var="usuario" itemValue="#{usuario}" itemLabel="#{usuario.nome}"
                                        multiple="false"
                                        completeMethod="#{instituicaoView.getPossiveisAlunos}"
                                        converter="#{genericEntityConverter}" forceSelection="true">
                            <p:column>
                                <h:graphicImage styleClass="avatarTopo" url="#{usuario.avatarUrl}" height="22" width="22" />
                            </p:column>
                            <p:column>
                                <h:outputText value="#{usuario.nomeCompleto}" />
                            </p:column>

                        </p:autoComplete>
                        <p:commandButton value="Convidar" action="#{instituicaoView.convidarAluno()}"/>
                        <br/>
                        <p:spacer height="10"/>
                        <p:dataTable value="#{instituicaoView.curso.alunosSet}"   
                                     rows="10"
                                     emptyMessage="Nenhum aluno encontrado."
                                     paginator="true"
                                     paginatorPosition="bottom"
                                     var="membro">
                            <p:column style="text-align: left; width: 24px;"> 
                                <h:button image="#{membro.avatarUrl}" styleClass="avatarComentario" 
                                          outcome="/usuario/visualizar.xhtml?faces-redirect=true" value="3">
                                    <f:param name="usuarioId" value="#{membro.id}"/>
                                </h:button>    
                            </p:column>
                            <p:column style="text-align: left;" filterStyle="width: 100%" filterBy="#{membro.nomeCompleto}" filterMatchMode="contains">
                                <p:outputLabel value="#{membro.nomeCompleto}"/>
                            </p:column>
                            <p:column width="140">
                                <p:commandButton value="Convidar para AVA"    
                                                 icon="ui-icon-plus"   
                                                 disabled="#{instituicaoView.conviteExistente(membro)}"
                                                 action="#{instituicaoView.convidarAlunoParaAva(membro)}"/>
                            </p:column>
                            <p:column width="140">
                                <p:commandButton value="Remover do curso"    
                                                 icon="ui-icon-minus"          
                                                 action="#{instituicaoView.removerAlunoDoCurso(membro)}"/>
                            </p:column>
                        </p:dataTable>
                        <p:outputLabel value="Convidar professor: "/>
                        <p:autoComplete id="usuariosprofessor" value="#{instituicaoView.professorConvidado}" 
                                        var="usuario" itemValue="#{usuario}" itemLabel="#{usuario.nome}"
                                        multiple="false"
                                        completeMethod="#{instituicaoView.getPossiveisProfessores}"
                                        converter="#{genericEntityConverter}" forceSelection="true">
                            <p:column>
                                <h:graphicImage styleClass="avatarTopo" url="#{usuario.avatarUrl}" height="22" width="22" />
                            </p:column>
                            <p:column>
                                <h:outputText value="#{usuario.nomeCompleto}" />
                            </p:column>

                        </p:autoComplete>
                        <p:commandButton value="Convidar" action="#{instituicaoView.convidarProfessor()}"/>
                        <br/>
                        <p:spacer height="10"/>
                        <p:dataTable value="#{instituicaoView.curso.professoresSet}"   
                                     rows="10"
                                     emptyMessage="Nenhum professor encontrado."
                                     paginator="true"
                                     paginatorPosition="bottom"
                                     var="membro">
                            <p:column style="text-align: left; width: 24px;"> 
                                <h:button image="#{membro.avatarUrl}" styleClass="avatarComentario" 
                                          outcome="/usuario/visualizar.xhtml?faces-redirect=true" value="3">
                                    <f:param name="usuarioId" value="#{membro.id}"/>
                                </h:button>    
                            </p:column>
                            <p:column style="text-align: left;" filterStyle="width: 100%" filterBy="#{membro.nomeCompleto}" filterMatchMode="contains">
                                <p:outputLabel value="#{membro.nomeCompleto}"/>
                            </p:column>
                            <p:column width="140">
                                <p:commandButton value="Convidar para AVA"    
                                                 icon="ui-icon-plus"          
                                                 disabled="#{instituicaoView.conviteExistente(membro)}"
                                                 action="#{instituicaoView.convidarProfessorParaAva(membro)}"/>
                            </p:column>
                            <p:column width="140">
                                <p:commandButton value="Remover do curso"    
                                                 icon="ui-icon-minus"          
                                                 action="#{instituicaoView.removerProfessorDoCurso(membro)}"/>
                            </p:column>
                        </p:dataTable>
                    </p:fieldset>
                </h:form>
            </ui:define>
        </ui:composition> 
    </h:body>
</html>

PortalDoEnsino/src/main/webapp/instituicao/administrarUsuarios.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <f:metadata>
        <f:viewParam name="instituicaoId" value="#{instituicaoView.instituicao.id}" />
        <f:viewAction action="#{instituicaoView.loadEdicao()}" if="#{not empty param['instituicaoId']}"/>
    </f:metadata>
    <h:body>
        <ui:composition template="/resources/template/layout.xhtml">
            <ui:define name="conteudo">
                <h:form styleClass="tema" rendered="#{sessionController.loggedIn and instituicaoView.instituicao.ehAdministrador(sessionController.usuarioLogado)}"> 
                    <p:fieldset legend="Instituição #{instituicaoView.instituicao.nome}" >
                        <p:commandButton value="Voltar para a instituição" ajax="false" 
                                         icon="ui-icon-arrowreturn-1-w"
                                         rendered="#{!instituicaoView.instituicao.new}" action="#{instituicaoView.voltarParaInstituicao()}"/>
                        <br/>
                        <p:outputLabel value="Convidar usuário para administração: "/>
                        <p:autoComplete id="usuarios" value="#{instituicaoView.usuarioConvidado}" 
                                        var="usuario" itemValue="#{usuario}" itemLabel="#{usuario.nome}"
                                        multiple="false"
                                        completeMethod="#{instituicaoView.getUsuarios}"
                                        converter="#{genericEntityConverter}" forceSelection="true">
                            <p:column>
                                <h:graphicImage styleClass="avatarTopo" url="#{usuario.avatarUrl}" height="22" width="22" />
                            </p:column>
                            <p:column>
                                <h:outputText value="#{usuario.nomeCompleto}" />
                            </p:column>

                        </p:autoComplete>
                        <p:commandButton value="Convidar" action="#{instituicaoView.convidarAdministrador()}"/>
                        <br/>
                        <p:spacer height="10"/>
                        <p:dataTable value="#{instituicaoView.instituicao.administradoresSet}"   
                                     rows="50"
                                     emptyMessage="Nenhum membro encontrado."
                                     paginator="true"
                                     paginatorPosition="bottom"
                                     var="membro">
                            <p:column style="text-align: left; width: 24px;"> 
                                <h:button image="#{membro.avatarUrl}" styleClass="avatarComentario" 
                                          outcome="/usuario/visualizar.xhtml?faces-redirect=true" value="3">
                                    <f:param name="usuarioId" value="#{membro.id}"/>
                                </h:button>    
                            </p:column>
                            <p:column style="text-align: left;" filterStyle="width: 100%" filterBy="#{membro.nomeCompleto}" filterMatchMode="contains">
                                <p:outputLabel value="#{membro.nomeCompleto}"/>
                            </p:column>
                            <p:column width="140">
                                <p:commandButton value="Remover da instituição"    
                                                 icon="ui-icon-minus"          
                                                 action="#{instituicaoView.removerDaInstituicao(membro)}"/>
                            </p:column>
                        </p:dataTable>
                    </p:fieldset>
                </h:form>
            </ui:define>
        </ui:composition> 
    </h:body>
</html>