PortalDoEnsino/src/main/java/br/com/portaldoensino/entity/Mensagem.java
package br.com.portaldoensino.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.Objects;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 *
 * @author jose.bonifacio
 */
@Entity
@Table(name = "mensagem")
public class Mensagem implements PersistentEntity<Long>, Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @NotNull
    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    private Date dataEnvio;
    @NotNull
    @ManyToOne
    private Usuario usuarioEnvio;
    private Boolean visualizado;
    @NotNull
    @ManyToOne
    private Usuario usuarioRecebimento;
    @ManyToOne
    private Mensagem mensagemPai;
    @Size
    private String titulo;
    @Size(max = 5000)
    private String mensagem;

    public Mensagem() {
    }    
        
    @Override
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }
    
    public Date getDataEnvio() {
        return dataEnvio;
    }

    public void setDataEnvio(Date dataEnvio) {
        this.dataEnvio = dataEnvio;
    }


    public Usuario getUsuarioEnvio() {
        return usuarioEnvio;
    }

    public void setUsuarioEnvio(Usuario usuarioEnvio) {
        this.usuarioEnvio = usuarioEnvio;
    }

    public Usuario getUsuarioRecebimento() {
        return usuarioRecebimento;
    }

    public void setUsuarioRecebimento(Usuario usuarioRecebimento) {
        this.usuarioRecebimento = usuarioRecebimento;
    }    
    
    public Boolean getVisualizado() {
        return visualizado;
    }

    public void setVisualizado(Boolean visualizado) {
        this.visualizado = visualizado;
    }
    
   
    public String getMensagem() {
        return mensagem;
    }

    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }

    public Mensagem getMensagemPai() {
        return mensagemPai;
    }

    public void setMensagemPai(Mensagem mensagemPai) {
        this.mensagemPai = mensagemPai;
    }

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    
    public boolean isNew() {
        return this.id == null;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Mensagem other = (Mensagem) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }
                   
}

PortalDoEnsino/src/main/java/br/com/portaldoensino/entity/Usuario.java
package br.com.portaldoensino.entity;

import br.com.portaldoensino.util.SenhaUtil;
import java.io.Serializable;
import java.util.List;
import java.util.Objects;
import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 *
 * @author jose.bonifacio
 */
@Entity
@Table(name = "usuario")
public class Usuario implements PersistentEntity<Long>, Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @NotNull
    private String email;
    @NotNull
    private String senha;
    @NotNull
    private String nome;
    private String sobrenome;
    private String avatar;
    @NotNull
    private Boolean ativo;
    @OneToMany(mappedBy = "usuario",
            fetch = FetchType.EAGER,
            cascade = CascadeType.ALL)
    private List<UsuarioAmigo> amigos;
    @OneToMany(mappedBy = "usuario",
            fetch = FetchType.EAGER,
            cascade = CascadeType.ALL)
    private List<UsuarioSeguidor> usuariosSeguidos;
    @OneToMany(mappedBy = "tema",
            fetch = FetchType.LAZY,
            cascade = CascadeType.ALL)
    private List<TemaFavorito> temasFavoritos;
    @OneToMany(mappedBy = "usuario",
            fetch = FetchType.EAGER,
            cascade = CascadeType.ALL)
    private List<InstituicaoSeguida> instituicoesSeguidas;

    public Usuario() {
        ativo = true;
    }

    @Override
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = SenhaUtil.getEncryptedPassword(senha);
    }

    public void setSenhaCriptografada(String senhaCriptografada) {
        this.senha = senhaCriptografada;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getSobrenome() {
        return sobrenome;
    }

    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Boolean getAtivo() {
        return ativo;
    }

    public void setAtivo(Boolean ativo) {
        this.ativo = ativo;
    }

    public String getNomeCompleto() {
        return this.nome.concat(" ").concat(this.sobrenome);
    }

    public String getAvatar() {
        return avatar;
    }

    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    public String getAvatarUrl() {
        if (avatar == null || avatar.isEmpty()) {
            return "http://localhost:8080/PortalDoEnsino/faces/download?caminhoArquivo="
                    + "C:/PortalDoEnsino/portaldoensino/PortalDoEnsino/src/main/webapp/resources/images/defaultavatar2.png";
        }
        return "http://localhost:8080/PortalDoEnsino/faces/download?caminhoArquivo=" + avatar;
    }

    public List<UsuarioAmigo> getAmigos() {
        return amigos;
    }

    public boolean ehAmigo(Usuario usuario) {
        boolean ehAmigo = false;
        if (usuario == null) {
            return false;
        }
        for (UsuarioAmigo amigo : amigos) {
            if (amigo.getAmigo().getId().equals(usuario.getId())) {
                ehAmigo = true;
            }
        }
        return ehAmigo;
    }

    public boolean ehSeguido(Usuario usuario) {
        boolean ehSeguido = false;
        if (usuario == null) {
            return false;
        }
        for (UsuarioSeguidor usuarioSeguido : usuariosSeguidos) {
            if (usuarioSeguido.getSeguidor().getId().equals(usuario.getId())) {
                ehSeguido = true;
            }
        }
        return ehSeguido;
    }

    public void setAmigos(List<UsuarioAmigo> amigos) {
        this.amigos = amigos;
    }

    public List<UsuarioSeguidor> getUsuariosSeguidos() {
        return usuariosSeguidos;
    }

    public void setUsuariosSeguidos(List<UsuarioSeguidor> usuariosSeguidos) {
        this.usuariosSeguidos = usuariosSeguidos;
    }

    public List<TemaFavorito> getTemasFavoritos() {
        return temasFavoritos;
    }

    public void setTemasFavoritos(List<TemaFavorito> temasFavoritos) {
        this.temasFavoritos = temasFavoritos;
    }

    public List<InstituicaoSeguida> getInstituicoesSeguidas() {
        return instituicoesSeguidas;
    }

    public void setInstituicoesSeguidas(List<InstituicaoSeguida> instituicoesSeguidas) {
        this.instituicoesSeguidas = instituicoesSeguidas;
    }

    public String getUrlPerfil() {
        return "<a href=\"http://localhost:8080/PortalDoEnsino/faces/usuario/visualizar.xhtml?usuarioId=" + id + "\">" + getNomeCompleto() + "</a>";
    }

    public String getUrlPerfil(Usuario usuario) {
        return "<a href=\"http://localhost:8080/PortalDoEnsino/faces/usuario/visualizar.xhtml?usuarioId=" + usuario.getId() + "\">" + usuario.getNomeCompleto() + "</a>";
    }

    @Override
    public boolean isNew() {
        return this.id == null;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Usuario other = (Usuario) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return String.valueOf(id);
    }

}

PortalDoEnsino/src/main/webapp/secured/mensagem/mensagem.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:body>
        <ui:composition template="/resources/template/layout.xhtml">
            <f:metadata>
                <f:viewParam name="mensagemId" value="#{mensagemView.mensagemPai.id}" />
                <f:viewParam name="usuarioId" value="#{mensagemView.usuarioRecebimento.id}"/>
                <f:viewAction action="#{mensagemView.carregarUsuarioRecebimento()}" if="#{not empty param['usuarioId']}" />
                <f:viewAction action="#{mensagemView.carregarMensagens()}" if="#{not empty param['mensagemId']}" />
            </f:metadata>

            <ui:define name="conteudo">
                <h:form styleClass="mensagens">
                    <p:panelGrid style="width: 100%;" columns="2" rendered="#{mensagemView.mensagemPai.new}">
                        <p:outputLabel value="Para: "/>
                        <p:autoComplete id="usuarios" value="#{mensagemView.usuarioRecebimento}" 
                                        var="usuario" itemValue="#{usuario}" itemLabel="#{usuario.nome}"
                                        multiple="false"
                                        required="true"
                                        disabled="#{!mensagemView.usuarioRecebimento.new}"
                                        completeMethod="#{mensagemView.getUsuarios}"
                                        converter="#{genericEntityConverter}" forceSelection="true">
                            <p:column>
                                <h:graphicImage styleClass="avatarTopo" url="#{usuario.avatarUrl}" height="22" width="22" />
                            </p:column>
                            <p:column>
                                <h:outputText value="#{usuario.nomeCompleto}" />
                            </p:column>
                            <p:ajax event="itemSelect" update="@form" />        
                        </p:autoComplete>
                        <p:outputLabel value="Título: "/>
                        <p:inputText value="#{mensagemView.mensagem.titulo}"/>
                        <p:outputLabel value=""/>
                        <p:editor value="#{mensagemView.mensagem.mensagem}"/>
                        <p:outputLabel value=""/>                        
                        <p:commandButton value="Enviar mensagem" action="#{mensagemView.enviarMensagem()}"/>
                    </p:panelGrid>
                    <p:panelGrid style="width: 100%;" rendered="#{!mensagemView.mensagemPai.new}">
                        <f:facet name="header" >
                            <p:row>
                                <p:column colspan="1" style="width: 36px;" >
                                </p:column>
                                <p:column colspan="1" style="text-align: left; font-size: 20px;" >
                                    <p:outputLabel value="Mensagem: #{mensagemView.mensagemPai.titulo}"/>
                                </p:column>
                                <p:column colspan="1" style="width: 36px;" >
                                </p:column>
                            </p:row>
                        </f:facet>
                        <ui:repeat id="repeatMensagens" value="#{mensagemView.mensagens}"
                                   varStatus="mensagemIterator" var="mensagem">
                            <p:row>
                                <p:column colspan="1" >
                                    <h:button image="#{mensagem.usuarioEnvio.avatarUrl}" styleClass="avatarPublicacao" outcome="/usuario/visualizar.xhtml?faces-redirect=true" value="3">
                                        <f:param name="usuarioId" value="#{mensagem.usuarioEnvio.id}"/>
                                    </h:button>      
                                </p:column>
                                <p:column colspan="1" >
                                    <p:outputLabel value="#{mensagem.mensagem}"/>
                                </p:column>
                                <p:column colspan="1" style="width: 36px; text-align: right;">
                                    <h:outputText value="#{mensagem.dataEnvio}">                                              
                                        <f:converter converterId="timestampConverter" /> 
                                    </h:outputText>
                                </p:column>
                            </p:row>               
                        </ui:repeat>
                        <p:row>
                            <p:column colspan="3">
                                <p:editor value="#{mensagemView.mensagem.mensagem}"/>
                            </p:column>
                        </p:row>
                        <p:row>
                            <p:column colspan="3">
                                <p:commandButton value="Enviar mensagem" action="#{mensagemView.enviarMensagem()}" >
                                    <f:attribute value="#{mensagemView.mensagem.id}" name="mensagemId" />
                                </p:commandButton>
                            </p:column>
                        </p:row>
                    </p:panelGrid>      
                </h:form>
            </ui:define>
        </ui:composition> 
    </h:body>
</html>

PortalDoEnsino/src/main/webapp/secured/mensagem/mensagens.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:body>
        <ui:composition template="/resources/template/layout.xhtml">
            <ui:define name="conteudo">
                <h:form styleClass="mensagens">
                    <p:commandButton value="Nova mensagem" ajax="false" action="#{mensagemView.novaMensagem()}"/>
                    <br/>
                    <p:spacer height="10"/>
                    <p:dataTable value="#{mensagemView.mensagensRecebidas}"   
                                 emptyMessage="Sem mensagens"
                                 var="mensagem">
                        <p:column headerText="Ler" width="36">
                            <p:commandButton icon="#{mensagem.mensagensNaoLidas == 0 ? 'ui-icon-mail-open' : 'ui-icon-mail-closed'}"
                                             action="#{mensagemView.visualizarMensagens(mensagem.mensagemPai)}">
                            </p:commandButton>
                        </p:column>
                        <p:column headerText="Não lidas" width="40" style="text-align: center;">
                            <h:outputText value="#{mensagem.mensagensNaoLidas}"/>
                        </p:column>
                        <p:column headerText="Última mensagem" width="80" style="text-align: right;">
                            <h:outputText value="#{mensagem.ultimaMensagemEnviada}">                                              
                                <f:converter converterId="timestampConverter" /> 
                            </h:outputText>
                        </p:column>
                        <p:column headerText="Tíulo" style="text-align: left;">
                            <h:outputText value="#{mensagem.mensagemPai.titulo}"/>
                        </p:column>
                        <p:column width="32">
                            <h:button image="#{mensagem.mensagemPai.usuarioEnvio.id == sessionController.usuarioLogado.id
                                               ? mensagem.mensagemPai.usuarioRecebimento.avatarUrl
                                               : mensagem.mensagemPai.usuarioEnvio.avatarUrl}" styleClass="avatarPublicacao" outcome="/usuario/visualizar.xhtml?faces-redirect=true" value="3">
                                <f:param name="usuarioId"
                                         value="#{mensagem.mensagemPai.usuarioEnvio.id == sessionController.usuarioLogado.id
                                                  ? mensagem.mensagemPai.usuarioRecebimento.id
                                                  : mensagem.mensagemPai.usuarioEnvio.id}"/>
                            </h:button>      
                        </p:column>
                        <p:column headerText="Usuário" width="180" style="text-align: left;">
                            <h:outputText value="#{mensagem.mensagemPai.usuarioEnvio.id == sessionController.usuarioLogado.id 
                                                   ? mensagem.mensagemPai.usuarioRecebimento.nomeCompleto
                                                   : mensagem.mensagemPai.usuarioEnvio.nomeCompleto}"/>
                        </p:column>
                    </p:dataTable>
                </h:form>
            </ui:define>
        </ui:composition> 
    </h:body>
</html>